---
title: "Lab 12"
webr:
  show-startup-message: true
---

```{webr-r}
#| context: setup

Titanic<-structure(list(Survived = c(0L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 
1L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 1L, 0L, 1L, 1L, 1L, 0L, 
1L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 
0L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 1L, 
0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 
0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 0L, 1L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 1L, 0L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 
0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 
0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 
0L, 1L, 1L, 0L, 0L, 1L, 0L, 1L, 1L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 
0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 
0L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 
1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 
0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 
0L, 0L, 1L, 1L, 1L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 1L, 0L, 0L, 1L, 0L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 
0L, 1L, 1L, 1L, 1L, 0L, 1L, 0L, 1L, 1L, 1L, 0L, 1L, 1L, 1L, 0L, 
0L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 1L, 1L, 
1L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 
1L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 
0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 1L, 0L, 
1L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 0L, 1L, 0L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 1L, 1L, 0L, 1L, 1L, 1L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 1L, 
0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 
1L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 
1L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 0L, 
1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 
0L, 1L, 1L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 1L, 
0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 
1L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 0L, 
1L, 1L, 0L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
1L, 1L, 1L, 1L, 1L, 0L, 0L, 1L, 1L, 0L, 1L, 1L, 1L, 0L, 0L, 0L, 
1L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 
0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 
0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 1L, 
0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 1L, 0L, 1L, 0L, 
1L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 
0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 
1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 
1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 0L, 1L, 
0L, 0L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 0L, 
0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 1L, 
0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 
0L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 
1L, 0L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 
1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 
0L, 0L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 
0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 
1L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 
0L, 1L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 
1L, 0L), Pclass = c(3L, 1L, 3L, 1L, 3L, 3L, 1L, 3L, 3L, 2L, 3L, 
1L, 3L, 3L, 3L, 2L, 3L, 2L, 3L, 3L, 2L, 2L, 3L, 1L, 3L, 3L, 3L, 
1L, 3L, 3L, 1L, 1L, 3L, 2L, 1L, 1L, 3L, 3L, 3L, 3L, 3L, 2L, 3L, 
2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 1L, 2L, 1L, 1L, 2L, 3L, 2L, 
3L, 3L, 1L, 1L, 3L, 1L, 3L, 2L, 3L, 3L, 3L, 2L, 3L, 2L, 3L, 3L, 
3L, 3L, 3L, 2L, 3L, 3L, 3L, 3L, 1L, 2L, 3L, 3L, 3L, 1L, 3L, 3L, 
3L, 1L, 3L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 3L, 3L, 3L, 3L, 
3L, 3L, 3L, 1L, 3L, 3L, 3L, 3L, 3L, 3L, 2L, 1L, 3L, 2L, 3L, 2L, 
2L, 1L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 2L, 2L, 2L, 1L, 1L, 3L, 
1L, 3L, 3L, 3L, 3L, 2L, 2L, 3L, 3L, 2L, 2L, 2L, 1L, 3L, 3L, 3L, 
1L, 3L, 3L, 3L, 3L, 3L, 2L, 3L, 3L, 3L, 3L, 1L, 3L, 1L, 3L, 1L, 
3L, 3L, 3L, 1L, 3L, 3L, 1L, 2L, 3L, 3L, 2L, 3L, 2L, 3L, 1L, 3L, 
1L, 3L, 3L, 2L, 2L, 3L, 2L, 1L, 1L, 3L, 3L, 3L, 2L, 3L, 3L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 1L, 3L, 2L, 3L, 2L, 3L, 1L, 3L, 2L, 1L, 
2L, 3L, 2L, 3L, 3L, 1L, 3L, 2L, 3L, 2L, 3L, 1L, 3L, 2L, 3L, 2L, 
3L, 2L, 2L, 2L, 2L, 3L, 3L, 2L, 3L, 3L, 1L, 3L, 2L, 1L, 2L, 3L, 
3L, 1L, 3L, 3L, 3L, 1L, 1L, 1L, 2L, 3L, 3L, 1L, 1L, 3L, 2L, 3L, 
3L, 1L, 1L, 1L, 3L, 2L, 1L, 3L, 1L, 3L, 2L, 3L, 3L, 3L, 3L, 3L, 
3L, 1L, 3L, 3L, 3L, 2L, 3L, 1L, 1L, 2L, 3L, 3L, 1L, 3L, 1L, 1L, 
1L, 3L, 3L, 3L, 2L, 3L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 3L, 2L, 
3L, 2L, 2L, 1L, 1L, 3L, 3L, 2L, 2L, 3L, 1L, 3L, 2L, 3L, 1L, 3L, 
1L, 1L, 3L, 1L, 3L, 1L, 1L, 3L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 
3L, 3L, 3L, 3L, 1L, 3L, 3L, 3L, 3L, 1L, 2L, 3L, 3L, 3L, 2L, 3L, 
3L, 3L, 3L, 1L, 3L, 3L, 1L, 1L, 3L, 3L, 1L, 3L, 1L, 3L, 1L, 3L, 
3L, 1L, 3L, 3L, 1L, 3L, 2L, 3L, 2L, 3L, 2L, 1L, 3L, 3L, 1L, 3L, 
3L, 3L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 2L, 3L, 2L, 3L, 3L, 3L, 
3L, 1L, 2L, 3L, 3L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 2L, 
2L, 3L, 3L, 1L, 3L, 2L, 3L, 1L, 1L, 3L, 2L, 1L, 2L, 2L, 3L, 3L, 
2L, 3L, 1L, 2L, 1L, 3L, 1L, 2L, 3L, 1L, 1L, 3L, 3L, 1L, 1L, 2L, 
3L, 1L, 3L, 1L, 2L, 3L, 3L, 2L, 1L, 3L, 3L, 3L, 3L, 2L, 2L, 3L, 
1L, 2L, 3L, 3L, 3L, 3L, 2L, 3L, 3L, 1L, 3L, 1L, 1L, 3L, 3L, 3L, 
3L, 1L, 1L, 3L, 3L, 1L, 3L, 1L, 3L, 3L, 3L, 3L, 3L, 1L, 1L, 2L, 
1L, 3L, 3L, 3L, 3L, 1L, 1L, 3L, 1L, 2L, 3L, 2L, 3L, 1L, 3L, 3L, 
1L, 3L, 3L, 2L, 1L, 3L, 2L, 2L, 3L, 3L, 3L, 3L, 2L, 1L, 1L, 3L, 
1L, 1L, 3L, 3L, 2L, 1L, 1L, 2L, 2L, 3L, 2L, 1L, 2L, 3L, 3L, 3L, 
1L, 1L, 1L, 1L, 3L, 3L, 3L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 2L, 
1L, 1L, 3L, 3L, 3L, 2L, 1L, 3L, 3L, 2L, 1L, 2L, 1L, 3L, 1L, 2L, 
1L, 3L, 3L, 3L, 1L, 3L, 3L, 2L, 3L, 2L, 3L, 3L, 1L, 2L, 3L, 1L, 
3L, 1L, 3L, 3L, 1L, 2L, 1L, 3L, 3L, 3L, 3L, 3L, 2L, 3L, 3L, 2L, 
2L, 3L, 1L, 3L, 3L, 3L, 1L, 2L, 1L, 3L, 3L, 1L, 3L, 1L, 1L, 3L, 
2L, 3L, 2L, 3L, 3L, 3L, 1L, 3L, 3L, 3L, 1L, 3L, 1L, 3L, 3L, 3L, 
2L, 3L, 3L, 3L, 2L, 3L, 3L, 2L, 1L, 1L, 3L, 1L, 3L, 3L, 2L, 2L, 
3L, 3L, 1L, 2L, 1L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 1L, 3L, 1L, 3L, 
3L, 2L, 2L, 3L, 3L, 3L, 1L, 1L, 3L, 3L, 3L, 1L, 2L, 3L, 3L, 1L, 
3L, 1L, 1L, 3L, 3L, 3L, 2L, 2L, 1L, 1L, 3L, 1L, 1L, 1L, 3L, 2L, 
3L, 1L, 2L, 3L, 3L, 2L, 3L, 2L, 2L, 1L, 3L, 2L, 3L, 2L, 3L, 1L, 
3L, 2L, 2L, 2L, 3L, 3L, 1L, 3L, 3L, 1L, 1L, 1L, 3L, 3L, 1L, 3L, 
2L, 1L, 3L, 2L, 3L, 3L, 3L, 2L, 2L, 3L, 2L, 3L, 1L, 3L, 3L, 3L, 
1L, 3L, 1L, 1L, 3L, 3L, 3L, 3L, 3L, 2L, 3L, 2L, 3L, 3L, 3L, 3L, 
1L, 3L, 1L, 1L, 3L, 3L, 3L, 3L, 3L, 3L, 1L, 3L, 2L, 3L, 1L, 3L, 
2L, 1L, 3L, 3L, 3L, 2L, 2L, 1L, 3L, 3L, 3L, 1L, 3L, 2L, 1L, 3L, 
3L, 2L, 3L, 3L, 1L, 3L, 2L, 3L, 3L, 1L, 3L, 1L, 3L, 3L, 3L, 3L, 
2L, 3L, 1L, 3L, 2L, 3L, 3L, 3L, 1L, 3L, 3L, 3L, 1L, 3L, 2L, 1L, 
3L, 3L, 3L, 3L, 3L, 2L, 1L, 3L, 3L, 3L, 1L, 2L, 3L, 1L, 1L, 3L, 
3L, 3L, 2L, 1L, 3L, 2L, 2L, 2L, 1L, 3L, 3L, 3L, 1L, 1L, 3L, 2L, 
3L, 3L, 3L, 3L, 1L, 2L, 3L, 3L, 2L, 3L, 3L, 2L, 1L, 3L, 1L, 3L
), Gender = c("male", "female", "female", "female", "male", "male", 
"male", "male", "female", "female", "female", "female", "male", 
"male", "female", "female", "male", "male", "female", "female", 
"male", "male", "female", "male", "female", "female", "male", 
"male", "female", "male", "male", "female", "female", "male", 
"male", "male", "male", "male", "female", "female", "female", 
"female", "male", "female", "female", "male", "male", "female", 
"male", "female", "male", "male", "female", "female", "male", 
"male", "female", "male", "female", "male", "male", "female", 
"male", "male", "male", "male", "female", "male", "female", "male", 
"male", "female", "male", "male", "male", "male", "male", "male", 
"male", "female", "male", "male", "female", "male", "female", 
"female", "male", "male", "female", "male", "male", "male", "male", 
"male", "male", "male", "male", "male", "female", "male", "female", 
"male", "male", "male", "male", "male", "female", "male", "male", 
"female", "male", "female", "male", "female", "female", "male", 
"male", "male", "male", "female", "male", "male", "male", "female", 
"male", "male", "male", "male", "female", "male", "male", "male", 
"female", "female", "male", "male", "female", "male", "male", 
"male", "female", "female", "female", "male", "male", "male", 
"male", "female", "male", "male", "male", "female", "male", "male", 
"male", "male", "female", "male", "male", "male", "male", "female", 
"male", "male", "male", "male", "female", "female", "male", "male", 
"male", "male", "female", "male", "male", "male", "male", "female", 
"male", "male", "female", "male", "male", "male", "female", "male", 
"female", "male", "male", "male", "female", "male", "female", 
"male", "female", "female", "male", "male", "female", "female", 
"male", "male", "male", "male", "male", "female", "male", "male", 
"female", "male", "male", "female", "male", "male", "male", "female", 
"female", "male", "female", "male", "male", "male", "male", "male", 
"male", "male", "male", "male", "male", "female", "female", "male", 
"male", "female", "male", "female", "male", "female", "male", 
"male", "female", "female", "male", "male", "male", "male", "female", 
"female", "male", "male", "male", "female", "male", "male", "female", 
"female", "female", "female", "female", "female", "male", "male", 
"male", "male", "female", "male", "male", "male", "female", "female", 
"male", "male", "female", "male", "female", "female", "female", 
"male", "male", "female", "male", "male", "male", "male", "male", 
"male", "male", "male", "male", "female", "female", "female", 
"male", "female", "male", "male", "male", "female", "male", "female", 
"female", "male", "male", "female", "male", "male", "female", 
"female", "male", "female", "female", "female", "female", "male", 
"male", "female", "female", "male", "female", "female", "male", 
"male", "female", "female", "male", "female", "male", "female", 
"female", "female", "female", "male", "male", "male", "female", 
"male", "male", "female", "male", "male", "male", "female", "male", 
"male", "male", "female", "female", "female", "male", "male", 
"male", "male", "male", "male", "male", "male", "female", "female", 
"female", "female", "male", "male", "female", "male", "male", 
"male", "female", "female", "female", "female", "male", "male", 
"male", "male", "female", "female", "female", "male", "male", 
"male", "female", "female", "male", "female", "male", "male", 
"male", "female", "male", "female", "male", "male", "male", "female", 
"female", "male", "female", "male", "male", "female", "male", 
"male", "female", "male", "female", "male", "male", "male", "male", 
"female", "male", "male", "female", "male", "male", "female", 
"female", "female", "male", "female", "male", "male", "male", 
"female", "male", "male", "female", "female", "male", "male", 
"male", "female", "female", "male", "male", "female", "female", 
"female", "male", "male", "female", "male", "male", "female", 
"male", "male", "female", "male", "female", "male", "male", "male", 
"male", "male", "male", "male", "male", "female", "female", "male", 
"male", "male", "male", "male", "male", "male", "male", "male", 
"male", "female", "male", "male", "female", "female", "female", 
"male", "male", "male", "male", "female", "male", "male", "male", 
"female", "male", "female", "female", "male", "male", "male", 
"male", "male", "male", "male", "male", "male", "female", "male", 
"female", "male", "male", "female", "female", "female", "female", 
"male", "female", "male", "male", "male", "male", "male", "male", 
"female", "male", "male", "female", "male", "female", "male", 
"female", "male", "male", "female", "male", "male", "female", 
"male", "male", "male", "female", "male", "male", "female", "female", 
"female", "male", "female", "male", "female", "female", "female", 
"female", "male", "male", "male", "female", "male", "male", "male", 
"male", "male", "male", "male", "female", "male", "female", "male", 
"female", "female", "male", "male", "male", "male", "female", 
"male", "male", "female", "male", "male", "male", "female", "male", 
"female", "male", "male", "female", "female", "female", "male", 
"female", "female", "male", "male", "male", "female", "male", 
"male", "male", "male", "male", "female", "male", "female", "male", 
"male", "female", "male", "male", "male", "female", "male", "male", 
"male", "male", "male", "male", "male", "female", "female", "female", 
"male", "female", "male", "male", "female", "male", "female", 
"female", "male", "male", "male", "male", "male", "male", "male", 
"male", "female", "male", "male", "male", "male", "male", "male", 
"female", "female", "male", "male", "female", "male", "male", 
"female", "female", "male", "female", "male", "male", "male", 
"male", "female", "male", "female", "male", "female", "female", 
"male", "male", "female", "male", "male", "male", "male", "male", 
"male", "male", "male", "male", "male", "male", "female", "female", 
"male", "male", "male", "male", "male", "male", "female", "female", 
"male", "female", "male", "male", "male", "male", "male", "male", 
"male", "male", "female", "male", "female", "male", "male", "male", 
"male", "male", "female", "male", "male", "female", "male", "female", 
"male", "male", "male", "female", "male", "female", "male", "female", 
"male", "male", "male", "male", "male", "female", "female", "male", 
"male", "female", "male", "male", "male", "male", "male", "female", 
"female", "male", "female", "female", "male", "male", "male", 
"male", "male", "female", "male", "male", "male", "male", "male", 
"female", "male", "male", "male", "male", "female", "male", "male", 
"female", "male", "male", "male", "female", "male", "male", "male", 
"male", "female", "male", "male", "male", "female", "male", "female", 
"male", "female", "male", "male", "male", "male", "female", "male", 
"female", "male", "male", "female", "male", "female", "female", 
"female", "male", "male", "male", "male", "female", "male", "male", 
"male", "male", "male", "female", "male", "male", "male", "female", 
"female", "male", "female", "male", "female", "male", "male", 
"male", "male", "male", "female", "male", "female", "male", "male", 
"male", "female", "male", "male", "female", "male", "male", "male", 
"female", "male", "male", "female", "male", "male", "male", "male", 
"male", "female", "female", "male", "male", "male", "male", "female", 
"male", "male", "male", "male", "male", "male", "female", "male", 
"male", "male", "male", "male", "male", "female", "male", "male", 
"female", "female", "female", "female", "female", "male", "female", 
"male", "male", "male", "female", "female", "male", "female", 
"female", "male", "male", "male", "male", "female", "male", "male", 
"female", "female", "male", "male", "male", "female", "female", 
"male", "female", "male", "male", "female", "male", "female", 
"female", "male", "male"), Age = c(22, 38, 26, 35, 35, NA, 54, 
2, 27, 14, 4, 58, 20, 39, 14, 55, 2, NA, 31, NA, 35, 34, 15, 
28, 8, 38, NA, 19, NA, NA, 40, NA, NA, 66, 28, 42, NA, 21, 18, 
14, 40, 27, NA, 3, 19, NA, NA, NA, NA, 18, 7, 21, 49, 29, 65, 
NA, 21, 28.5, 5, 11, 22, 38, 45, 4, NA, NA, 29, 19, 17, 26, 32, 
16, 21, 26, 32, 25, NA, NA, 0.83, 30, 22, 29, NA, 28, 17, 33, 
16, NA, 23, 24, 29, 20, 46, 26, 59, NA, 71, 23, 34, 34, 28, NA, 
21, 33, 37, 28, 21, NA, 38, NA, 47, 14.5, 22, 20, 17, 21, 70.5, 
29, 24, 2, 21, NA, 32.5, 32.5, 54, 12, NA, 24, NA, 45, 33, 20, 
47, 29, 25, 23, 19, 37, 16, 24, NA, 22, 24, 19, 18, 19, 27, 9, 
36.5, 42, 51, 22, 55.5, 40.5, NA, 51, 16, 30, NA, NA, 44, 40, 
26, 17, 1, 9, NA, 45, NA, 28, 61, 4, 1, 21, 56, 18, NA, 50, 30, 
36, NA, NA, 9, 1, 4, NA, NA, 45, 40, 36, 32, 19, 19, 3, 44, 58, 
NA, 42, NA, 24, 28, NA, 34, 45.5, 18, 2, 32, 26, 16, 40, 24, 
35, 22, 30, NA, 31, 27, 42, 32, 30, 16, 27, 51, NA, 38, 22, 19, 
20.5, 18, NA, 35, 29, 59, 5, 24, NA, 44, 8, 19, 33, NA, NA, 29, 
22, 30, 44, 25, 24, 37, 54, NA, 29, 62, 30, 41, 29, NA, 30, 35, 
50, NA, 3, 52, 40, NA, 36, 16, 25, 58, 35, NA, 25, 41, 37, NA, 
63, 45, NA, 7, 35, 65, 28, 16, 19, NA, 33, 30, 22, 42, 22, 26, 
19, 36, 24, 24, NA, 23.5, 2, NA, 50, NA, NA, 19, NA, NA, 0.92, 
NA, 17, 30, 30, 24, 18, 26, 28, 43, 26, 24, 54, 31, 40, 22, 27, 
30, 22, NA, 36, 61, 36, 31, 16, NA, 45.5, 38, 16, NA, NA, 29, 
41, 45, 45, 2, 24, 28, 25, 36, 24, 40, NA, 3, 42, 23, NA, 15, 
25, NA, 28, 22, 38, NA, NA, 40, 29, 45, 35, NA, 30, 60, NA, NA, 
24, 25, 18, 19, 22, 3, NA, 22, 27, 20, 19, 42, 1, 32, 35, NA, 
18, 1, 36, NA, 17, 36, 21, 28, 23, 24, 22, 31, 46, 23, 28, 39, 
26, 21, 28, 20, 34, 51, 3, 21, NA, NA, NA, 33, NA, 44, NA, 34, 
18, 30, 10, NA, 21, 29, 28, 18, NA, 28, 19, NA, 32, 28, NA, 42, 
17, 50, 14, 21, 24, 64, 31, 45, 20, 25, 28, NA, 4, 13, 34, 5, 
52, 36, NA, 30, 49, NA, 29, 65, NA, 50, NA, 48, 34, 47, 48, NA, 
38, NA, 56, NA, 0.75, NA, 38, 33, 23, 22, NA, 34, 29, 22, 2, 
9, NA, 50, 63, 25, NA, 35, 58, 30, 9, NA, 21, 55, 71, 21, NA, 
54, NA, 25, 24, 17, 21, NA, 37, 16, 18, 33, NA, 28, 26, 29, NA, 
36, 54, 24, 47, 34, NA, 36, 32, 30, 22, NA, 44, NA, 40.5, 50, 
NA, 39, 23, 2, NA, 17, NA, 30, 7, 45, 30, NA, 22, 36, 9, 11, 
32, 50, 64, 19, NA, 33, 8, 17, 27, NA, 22, 22, 62, 48, NA, 39, 
36, NA, 40, 28, NA, NA, 24, 19, 29, NA, 32, 62, 53, 36, NA, 16, 
19, 34, 39, NA, 32, 25, 39, 54, 36, NA, 18, 47, 60, 22, NA, 35, 
52, 47, NA, 37, 36, NA, 49, NA, 49, 24, NA, NA, 44, 35, 36, 30, 
27, 22, 40, 39, NA, NA, NA, 35, 24, 34, 26, 4, 26, 27, 42, 20, 
21, 21, 61, 57, 21, 26, NA, 80, 51, 32, NA, 9, 28, 32, 31, 41, 
NA, 20, 24, 2, NA, 0.75, 48, 19, 56, NA, 23, NA, 18, 21, NA, 
18, 24, NA, 32, 23, 58, 50, 40, 47, 36, 20, 32, 25, NA, 43, NA, 
40, 31, 70, 31, NA, 18, 24.5, 18, 43, 36, NA, 27, 20, 14, 60, 
25, 14, 19, 18, 15, 31, 4, NA, 25, 60, 52, 44, NA, 49, 42, 18, 
35, 18, 25, 26, 39, 45, 42, 22, NA, 24, NA, 48, 29, 52, 19, 38, 
27, NA, 33, 6, 17, 34, 50, 27, 20, 30, NA, 25, 25, 29, 11, NA, 
23, 23, 28.5, 48, 35, NA, NA, NA, 36, 21, 24, 31, 70, 16, 30, 
19, 31, 4, 6, 33, 23, 48, 0.67, 28, 18, 34, 33, NA, 41, 20, 36, 
16, 51, NA, 30.5, NA, 32, 24, 48, 57, NA, 54, 18, NA, 5, NA, 
43, 13, 17, 29, NA, 25, 25, 18, 8, 1, 46, NA, 16, NA, NA, 25, 
39, 49, 31, 30, 30, 34, 31, 11, 0.42, 27, 31, 39, 18, 39, 33, 
26, 39, 35, 6, 30.5, NA, 23, 31, 43, 10, 52, 27, 38, 27, 2, NA, 
NA, 1, NA, 62, 15, 0.83, NA, 23, 18, 39, 21, NA, 32, NA, 20, 
16, 30, 34.5, 17, 42, NA, 35, 28, NA, 4, 74, 9, 16, 44, 18, 45, 
51, 24, NA, 41, 21, 48, NA, 24, 42, 27, 31, NA, 4, 26, 47, 33, 
47, 28, 15, 20, 19, NA, 56, 25, 33, 22, 28, 25, 39, 27, 19, NA, 
26, 32), SibSp = c(1L, 1L, 0L, 1L, 0L, 0L, 0L, 3L, 0L, 1L, 1L, 
0L, 0L, 1L, 0L, 0L, 4L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 3L, 1L, 0L, 
3L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 2L, 1L, 1L, 1L, 0L, 
1L, 0L, 0L, 1L, 0L, 2L, 1L, 4L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 
5L, 0L, 0L, 1L, 3L, 0L, 1L, 0L, 0L, 4L, 2L, 0L, 5L, 0L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 1L, 0L, 3L, 0L, 0L, 
0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 
0L, 0L, 1L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 4L, 2L, 0L, 1L, 
0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 2L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 8L, 0L, 0L, 0L, 0L, 4L, 0L, 0L, 1L, 0L, 0L, 0L, 
4L, 1L, 0L, 0L, 1L, 3L, 0L, 0L, 0L, 8L, 0L, 4L, 2L, 0L, 0L, 1L, 
0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 8L, 0L, 
0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 3L, 1L, 0L, 0L, 4L, 0L, 
0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 2L, 0L, 0L, 1L, 1L, 0L, 
1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 4L, 1L, 0L, 0L, 0L, 4L, 
1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 4L, 1L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 2L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 0L, 0L, 2L, 1L, 0L, 1L, 
0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 8L, 0L, 0L, 0L, 1L, 0L, 2L, 
0L, 0L, 2L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 3L, 0L, 0L, 0L, 0L, 0L, 
1L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 
0L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 3L, 1L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 1L, 0L, 0L, 5L, 0L, 0L, 0L, 1L, 0L, 2L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 0L, 1L, 0L, 3L, 0L, 
0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 
0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 1L, 2L, 2L, 1L, 0L, 1L, 0L, 1L, 
0L, 0L, 0L, 0L, 0L, 2L, 0L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 1L, 0L, 0L, 
0L, 1L, 1L, 0L, 0L, 5L, 0L, 0L, 0L, 1L, 3L, 1L, 0L, 0L, 1L, 1L, 
0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 2L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 4L, 4L, 1L, 1L, 0L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 
0L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 
2L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 
1L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 2L, 0L, 0L, 
0L, 0L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 1L, 0L, 0L, 1L, 1L, 1L, 2L, 
0L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 
0L, 0L, 1L, 0L, 1L, 0L, 0L, 3L, 0L, 2L, 1L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 2L, 0L, 1L, 0L, 0L, 2L, 0L, 0L, 0L, 1L, 2L, 0L, 
0L, 0L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 
5L, 1L, 1L, 4L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 
0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 3L, 0L, 1L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 2L, 1L, 0L, 1L, 1L, 
0L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
1L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 
0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 4L, 1L, 0L, 0L, 0L, 8L, 0L, 0L, 
0L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 4L, 0L, 0L, 0L, 1L, 0L, 3L, 1L, 0L, 0L, 0L, 4L, 0L, 0L, 
0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 8L, 0L, 0L, 1L, 4L, 0L, 1L, 0L, 1L, 0L, 1L, 0L, 0L, 
0L, 2L, 1L, 0L, 8L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 1L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L
), Parch = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 2L, 0L, 1L, 0L, 
0L, 5L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 5L, 0L, 2L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 
0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 2L, 2L, 
0L, 0L, 0L, 2L, 0L, 1L, 0L, 0L, 2L, 0L, 0L, 2L, 0L, 0L, 0L, 0L, 
0L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 0L, 2L, 0L, 0L, 0L, 
0L, 2L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 2L, 0L, 0L, 0L, 0L, 
1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 
2L, 0L, 0L, 0L, 0L, 1L, 0L, 2L, 2L, 0L, 0L, 0L, 0L, 2L, 0L, 1L, 
0L, 0L, 0L, 2L, 1L, 0L, 0L, 0L, 1L, 2L, 1L, 4L, 0L, 0L, 0L, 1L, 
1L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 2L, 0L, 2L, 1L, 2L, 0L, 0L, 0L, 
1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 2L, 0L, 0L, 
0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 2L, 0L, 0L, 
0L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 1L, 0L, 0L, 1L, 
0L, 0L, 2L, 2L, 0L, 0L, 0L, 1L, 0L, 2L, 1L, 0L, 0L, 0L, 1L, 0L, 
1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 1L, 
0L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 2L, 1L, 0L, 1L, 0L, 
0L, 0L, 2L, 1L, 0L, 0L, 0L, 1L, 2L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 
1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 
1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 4L, 0L, 1L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 2L, 0L, 0L, 
0L, 2L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 2L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 
0L, 0L, 0L, 0L, 1L, 2L, 0L, 2L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 2L, 3L, 4L, 0L, 1L, 0L, 0L, 0L, 
0L, 2L, 1L, 0L, 1L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 2L, 0L, 0L, 0L, 
0L, 0L, 0L, 1L, 2L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 
0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 1L, 2L, 0L, 2L, 0L, 0L, 0L, 2L, 
2L, 2L, 2L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 2L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 4L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 2L, 0L, 1L, 
0L, 0L, 0L, 0L, 0L, 2L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 2L, 0L, 5L, 0L, 0L, 0L, 0L, 2L, 1L, 0L, 1L, 0L, 
0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 
0L, 1L, 5L, 0L, 0L, 0L, 2L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 
0L, 0L, 0L, 0L, 0L, 1L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 6L, 1L, 0L, 0L, 0L, 2L, 
1L, 2L, 1L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 
0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 0L, 3L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 0L, 1L, 1L, 0L, 
0L, 0L, 1L, 1L, 0L, 0L, 2L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 2L, 
0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 0L, 0L, 0L, 0L, 1L, 
0L, 0L, 0L, 2L, 0L, 0L, 0L, 1L, 2L, 0L, 0L, 0L, 2L, 0L, 0L, 0L, 
0L, 0L, 0L, 1L, 0L, 1L, 2L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 2L, 0L, 0L, 0L, 1L, 0L, 2L, 1L, 0L, 0L, 1L, 1L, 0L, 0L, 2L, 
0L, 0L, 0L, 1L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
0L, 0L, 2L, 0L, 1L, 0L, 2L, 0L, 1L, 1L, 0L, 1L, 1L, 0L, 3L, 0L, 
0L, 0L, 0L, 2L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 
0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 0L, 5L, 0L, 0L, 2L, 0L, 0L), 
    Ticket = c("A/5 21171", "PC 17599", "STON/O2. 3101282", "113803", 
    "373450", "330877", "17463", "349909", "347742", "237736", 
    "PP 9549", "113783", "A/5. 2151", "347082", "350406", "248706", 
    "382652", "244373", "345763", "2649", "239865", "248698", 
    "330923", "113788", "349909", "347077", "2631", "19950", 
    "330959", "349216", "PC 17601", "PC 17569", "335677", "C.A. 24579", 
    "PC 17604", "113789", "2677", "A./5. 2152", "345764", "2651", 
    "7546", "11668", "349253", "SC/Paris 2123", "330958", "S.C./A.4. 23567", 
    "370371", "14311", "2662", "349237", "3101295", "A/4. 39886", 
    "PC 17572", "2926", "113509", "19947", "C.A. 31026", "2697", 
    "C.A. 34651", "CA 2144", "2669", "113572", "36973", "347088", 
    "PC 17605", "2661", "C.A. 29395", "S.P. 3464", "3101281", 
    "315151", "C.A. 33111", "CA 2144", "S.O.C. 14879", "2680", 
    "1601", "348123", "349208", "374746", "248738", "364516", 
    "345767", "345779", "330932", "113059", "SO/C 14885", "3101278", 
    "W./C. 6608", "SOTON/OQ 392086", "19950", "343275", "343276", 
    "347466", "W.E.P. 5734", "C.A. 2315", "364500", "374910", 
    "PC 17754", "PC 17759", "231919", "244367", "349245", "349215", 
    "35281", "7540", "3101276", "349207", "343120", "312991", 
    "349249", "371110", "110465", "2665", "324669", "4136", "2627", 
    "STON/O 2. 3101294", "370369", "11668", "PC 17558", "347082", 
    "S.O.C. 14879", "A4. 54510", "237736", "27267", "35281", 
    "2651", "370372", "C 17369", "2668", "347061", "349241", 
    "SOTON/O.Q. 3101307", "A/5. 3337", "228414", "C.A. 29178", 
    "SC/PARIS 2133", "11752", "113803", "7534", "PC 17593", "2678", 
    "347081", "STON/O2. 3101279", "365222", "231945", "C.A. 33112", 
    "350043", "W./C. 6608", "230080", "244310", "S.O.P. 1166", 
    "113776", "A.5. 11206", "A/5. 851", "Fa 265302", "PC 17597", 
    "35851", "SOTON/OQ 392090", "315037", "CA. 2343", "371362", 
    "C.A. 33595", "347068", "315093", "3101295", "363291", "113505", 
    "347088", "PC 17318", "1601", "111240", "382652", "347742", 
    "STON/O 2. 3101280", "17764", "350404", "4133", "PC 17595", 
    "250653", "LINE", "CA. 2343", "SC/PARIS 2131", "347077", 
    "230136", "315153", "113767", "370365", "111428", "364849", 
    "349247", "234604", "28424", "350046", "230080", "PC 17610", 
    "PC 17569", "368703", "4579", "370370", "248747", "345770", 
    "CA. 2343", "3101264", "2628", "A/5 3540", "347054", "3101278", 
    "2699", "367231", "112277", "SOTON/O.Q. 3101311", "F.C.C. 13528", 
    "A/5 21174", "250646", "367229", "35273", "STON/O2. 3101283", 
    "243847", "11813", "W/C 14208", "SOTON/OQ 392089", "220367", 
    "21440", "349234", "19943", "PP 4348", "SW/PP 751", "A/5 21173", 
    "236171", "4133", "36973", "347067", "237442", "347077", 
    "C.A. 29566", "W./C. 6609", "26707", "C.A. 31921", "28665", 
    "SCO/W 1585", "2665", "367230", "W./C. 14263", "STON/O 2. 3101275", 
    "2694", "19928", "347071", "250649", "11751", "244252", "362316", 
    "347054", "113514", "A/5. 3336", "370129", "2650", "PC 17585", 
    "110152", "PC 17755", "230433", "384461", "347077", "110413", 
    "112059", "382649", "C.A. 17248", "3101295", "347083", "PC 17582", 
    "PC 17760", "113798", "LINE", "250644", "PC 17596", "370375", 
    "13502", "347073", "239853", "382652", "C.A. 2673", "336439", 
    "347464", "345778", "A/5. 10482", "113056", "349239", "345774", 
    "349206", "237798", "370373", "19877", "11967", "SC/Paris 2163", 
    "349236", "349233", "PC 17612", "2693", "113781", "19988", 
    "PC 17558", "9234", "367226", "LINE", "226593", "A/5 2466", 
    "113781", "17421", "PC 17758", "P/PP 3381", "PC 17485", "11767", 
    "PC 17608", "250651", "349243", "F.C.C. 13529", "347470", 
    "244367", "29011", "36928", "16966", "A/5 21172", "349219", 
    "234818", "248738", "CA. 2343", "PC 17760", "345364", "28551", 
    "363291", "111361", "367226", "113043", "PC 17582", "345764", 
    "PC 17611", "349225", "113776", "16966", "7598", "113784", 
    "230080", "19950", "248740", "244361", "229236", "248733", 
    "31418", "386525", "C.A. 37671", "315088", "7267", "113510", 
    "2695", "349237", "2647", "345783", "113505", "237671", "330931", 
    "330980", "347088", "SC/PARIS 2167", "2691", "SOTON/O.Q. 3101310", 
    "370365", "C 7076", "110813", "2626", "14313", "PC 17477", 
    "11765", "3101267", "323951", "PC 17760", "349909", "PC 17604", 
    "C 7077", "113503", "2648", "347069", "PC 17757", "2653", 
    "STON/O 2. 3101293", "113789", "349227", "S.O.C. 14879", 
    "CA 2144", "27849", "367655", "SC 1748", "113760", "350034", 
    "3101277", "35273", "PP 9549", "350052", "350407", "28403", 
    "244278", "240929", "STON/O 2. 3101289", "341826", "4137", 
    "STON/O2. 3101279", "315096", "28664", "347064", "29106", 
    "312992", "4133", "349222", "394140", "19928", "239853", 
    "STON/O 2. 3101269", "343095", "28220", "250652", "28228", 
    "345773", "349254", "A/5. 13032", "315082", "347080", "370129", 
    "A/4. 34244", "2003", "250655", "364851", "SOTON/O.Q. 392078", 
    "110564", "376564", "SC/AH 3085", "STON/O 2. 3101274", "13507", 
    "113760", "W./C. 6608", "29106", "19950", "C.A. 18723", "F.C.C. 13529", 
    "345769", "347076", "230434", "65306", "33638", "250644", 
    "113794", "2666", "113786", "C.A. 34651", "65303", "113051", 
    "17453", "A/5 2817", "349240", "13509", "17464", "F.C.C. 13531", 
    "371060", "19952", "364506", "111320", "234360", "A/S 2816", 
    "SOTON/O.Q. 3101306", "239853", "113792", "36209", "2666", 
    "323592", "315089", "C.A. 34651", "SC/AH Basle 541", "7553", 
    "110465", "31027", "3460", "350060", "3101298", "CA 2144", 
    "239854", "A/5 3594", "4134", "11967", "4133", "19943", "11771", 
    "A.5. 18509", "C.A. 37671", "65304", "SOTON/OQ 3101317", 
    "113787", "PC 17609", "A/4 45380", "2627", "36947", "C.A. 6212", 
    "113781", "350035", "315086", "364846", "330909", "4135", 
    "110152", "PC 17758", "26360", "111427", "C 4001", "1601", 
    "382651", "SOTON/OQ 3101316", "PC 17473", "PC 17603", "349209", 
    "36967", "C.A. 34260", "371110", "226875", "349242", "12749", 
    "349252", "2624", "111361", "2700", "367232", "W./C. 14258", 
    "PC 17483", "3101296", "29104", "26360", "2641", "2690", 
    "2668", "315084", "F.C.C. 13529", "113050", "PC 17761", "364498", 
    "13568", "WE/P 5735", "347082", "347082", "2908", "PC 17761", 
    "693", "2908", "SC/PARIS 2146", "363291", "C.A. 33112", "17421", 
    "244358", "330979", "2620", "347085", "113807", "11755", 
    "PC 17757", "110413", "345572", "372622", "349251", "218629", 
    "SOTON/OQ 392082", "SOTON/O.Q. 392087", "A/4 48871", "349205", 
    "349909", "2686", "350417", "S.W./PP 752", "11769", "PC 17474", 
    "14312", "A/4. 20589", "358585", "243880", "13507", "2689", 
    "STON/O 2. 3101286", "237789", "17421", "28403", "13049", 
    "3411", "110413", "237565", "13567", "14973", "A./5. 3235", 
    "STON/O 2. 3101273", "36947", "A/5 3902", "364848", "SC/AH 29037", 
    "345773", "248727", "LINE", "2664", "PC 17485", "243847", 
    "349214", "113796", "364511", "111426", "349910", "349246", 
    "113804", "SC/Paris 2123", "PC 17582", "347082", "SOTON/O.Q. 3101305", 
    "367230", "370377", "364512", "220845", "347080", "A/5. 3336", 
    "230136", "31028", "2659", "11753", "2653", "350029", "54636", 
    "36963", "219533", "13502", "349224", "334912", "27042", 
    "347743", "13214", "112052", "347088", "237668", "STON/O 2. 3101292", 
    "C.A. 31921", "3101295", "376564", "350050", "PC 17477", 
    "347088", "1601", "2666", "PC 17572", "349231", "13213", 
    "S.O./P.P. 751", "CA. 2314", "349221", "231919", "8475", 
    "330919", "365226", "S.O.C. 14879", "349223", "364849", "29751", 
    "35273", "PC 17611", "2623", "5727", "349210", "STON/O 2. 3101285", 
    "S.O.C. 14879", "234686", "312993", "A/5 3536", "19996", 
    "29750", "F.C. 12750", "C.A. 24580", "244270", "239856", 
    "349912", "342826", "4138", "CA 2144", "PC 17755", "330935", 
    "PC 17572", "6563", "CA 2144", "29750", "SC/Paris 2123", 
    "3101295", "349228", "350036", "24160", "17474", "349256", 
    "1601", "2672", "113800", "248731", "363592", "35852", "17421", 
    "348121", "PC 17757", "PC 17475", "2691", "36864", "350025", 
    "250655", "223596", "PC 17476", "113781", "2661", "PC 17482", 
    "113028", "19996", "7545", "250647", "348124", "PC 17757", 
    "34218", "36568", "347062", "248727", "350048", "12233", 
    "250643", "113806", "315094", "31027", "36866", "236853", 
    "STON/O2. 3101271", "24160", "2699", "239855", "28425", "233639", 
    "54636", "W./C. 6608", "PC 17755", "349201", "349218", "16988", 
    "19877", "PC 17608", "376566", "STON/O 2. 3101288", "WE/P 5735", 
    "C.A. 2673", "250648", "113773", "335097", "29103", "392096", 
    "345780", "349204", "220845", "250649", "350042", "29108", 
    "363294", "110152", "358585", "SOTON/O2 3101272", "2663", 
    "113760", "347074", "13502", "112379", "364850", "371110", 
    "8471", "345781", "350047", "S.O./P.P. 3", "2674", "29105", 
    "347078", "383121", "364516", "36865", "24160", "2687", "17474", 
    "113501", "W./C. 6607", "SOTON/O.Q. 3101312", "374887", "3101265", 
    "382652", "C.A. 2315", "PC 17593", "12460", "239865", "CA. 2343", 
    "PC 17600", "349203", "28213", "17465", "349244", "2685", 
    "345773", "250647", "C.A. 31921", "113760", "2625", "347089", 
    "347063", "112050", "347087", "248723", "113806", "3474", 
    "A/4 48871", "28206", "347082", "364499", "112058", "STON/O2. 3101290", 
    "S.C./PARIS 2079", "C 7075", "347088", "12749", "315098", 
    "19972", "392096", "3101295", "368323", "1601", "S.C./PARIS 2079", 
    "367228", "113572", "2659", "29106", "2671", "347468", "2223", 
    "PC 17756", "315097", "392092", "1601", "11774", "SOTON/O2 3101287", 
    "S.O./P.P. 3", "113798", "2683", "315090", "C.A. 5547", "CA. 2343", 
    "349213", "248727", "17453", "347082", "347060", "2678", 
    "PC 17592", "244252", "392091", "36928", "113055", "2666", 
    "2629", "350026", "28134", "17466", "CA. 2343", "233866", 
    "236852", "SC/PARIS 2149", "PC 17590", "345777", "347742", 
    "349248", "11751", "695", "345765", "P/PP 3381", "2667", 
    "7534", "349212", "349217", "11767", "230433", "349257", 
    "7552", "C.A./SOTON 34068", "SOTON/OQ 392076", "382652", 
    "211536", "112053", "W./C. 6607", "111369", "370376"), Fare = c(7.25, 
    71.2833, 7.925, 53.1, 8.05, 8.4583, 51.8625, 21.075, 11.1333, 
    30.0708, 16.7, 26.55, 8.05, 31.275, 7.8542, 16, 29.125, 13, 
    18, 7.225, 26, 13, 8.0292, 35.5, 21.075, 31.3875, 7.225, 
    263, 7.8792, 7.8958, 27.7208, 146.5208, 7.75, 10.5, 82.1708, 
    52, 7.2292, 8.05, 18, 11.2417, 9.475, 21, 7.8958, 41.5792, 
    7.8792, 8.05, 15.5, 7.75, 21.6792, 17.8, 39.6875, 7.8, 76.7292, 
    26, 61.9792, 35.5, 10.5, 7.2292, 27.75, 46.9, 7.2292, 80, 
    83.475, 27.9, 27.7208, 15.2458, 10.5, 8.1583, 7.925, 8.6625, 
    10.5, 46.9, 73.5, 14.4542, 56.4958, 7.65, 7.8958, 8.05, 29, 
    12.475, 9, 9.5, 7.7875, 47.1, 10.5, 15.85, 34.375, 8.05, 
    263, 8.05, 8.05, 7.8542, 61.175, 20.575, 7.25, 8.05, 34.6542, 
    63.3583, 23, 26, 7.8958, 7.8958, 77.2875, 8.6542, 7.925, 
    7.8958, 7.65, 7.775, 7.8958, 24.15, 52, 14.4542, 8.05, 9.825, 
    14.4583, 7.925, 7.75, 21, 247.5208, 31.275, 73.5, 8.05, 30.0708, 
    13, 77.2875, 11.2417, 7.75, 7.1417, 22.3583, 6.975, 7.8958, 
    7.05, 14.5, 26, 13, 15.0458, 26.2833, 53.1, 9.2167, 79.2, 
    15.2458, 7.75, 15.85, 6.75, 11.5, 36.75, 7.7958, 34.375, 
    26, 13, 12.525, 66.6, 8.05, 14.5, 7.3125, 61.3792, 7.7333, 
    8.05, 8.6625, 69.55, 16.1, 15.75, 7.775, 8.6625, 39.6875, 
    20.525, 55, 27.9, 25.925, 56.4958, 33.5, 29.125, 11.1333, 
    7.925, 30.6958, 7.8542, 25.4667, 28.7125, 13, 0, 69.55, 15.05, 
    31.3875, 39, 22.025, 50, 15.5, 26.55, 15.5, 7.8958, 13, 13, 
    7.8542, 26, 27.7208, 146.5208, 7.75, 8.4042, 7.75, 13, 9.5, 
    69.55, 6.4958, 7.225, 8.05, 10.4625, 15.85, 18.7875, 7.75, 
    31, 7.05, 21, 7.25, 13, 7.75, 113.275, 7.925, 27, 76.2917, 
    10.5, 8.05, 13, 8.05, 7.8958, 90, 9.35, 10.5, 7.25, 13, 25.4667, 
    83.475, 7.775, 13.5, 31.3875, 10.5, 7.55, 26, 26.25, 10.5, 
    12.275, 14.4542, 15.5, 10.5, 7.125, 7.225, 90, 7.775, 14.5, 
    52.5542, 26, 7.25, 10.4625, 26.55, 16.1, 20.2125, 15.2458, 
    79.2, 86.5, 512.3292, 26, 7.75, 31.3875, 79.65, 0, 7.75, 
    10.5, 39.6875, 7.775, 153.4625, 135.6333, 31, 0, 19.5, 29.7, 
    7.75, 77.9583, 7.75, 0, 29.125, 20.25, 7.75, 7.8542, 9.5, 
    8.05, 26, 8.6625, 9.5, 7.8958, 13, 7.75, 78.85, 91.0792, 
    12.875, 8.85, 7.8958, 27.7208, 7.2292, 151.55, 30.5, 247.5208, 
    7.75, 23.25, 0, 12.35, 8.05, 151.55, 110.8833, 108.9, 24, 
    56.9292, 83.1583, 262.375, 26, 7.8958, 26.25, 7.8542, 26, 
    14, 164.8667, 134.5, 7.25, 7.8958, 12.35, 29, 69.55, 135.6333, 
    6.2375, 13, 20.525, 57.9792, 23.25, 28.5, 153.4625, 18, 133.65, 
    7.8958, 66.6, 134.5, 8.05, 35.5, 26, 263, 13, 13, 13, 13, 
    13, 16.1, 15.9, 8.6625, 9.225, 35, 7.2292, 17.8, 7.225, 9.5, 
    55, 13, 7.8792, 7.8792, 27.9, 27.7208, 14.4542, 7.05, 15.5, 
    7.25, 75.25, 7.2292, 7.75, 69.3, 55.4417, 6.4958, 8.05, 135.6333, 
    21.075, 82.1708, 7.25, 211.5, 4.0125, 7.775, 227.525, 15.7417, 
    7.925, 52, 7.8958, 73.5, 46.9, 13, 7.7292, 12, 120, 7.7958, 
    7.925, 113.275, 16.7, 7.7958, 7.8542, 26, 10.5, 12.65, 7.925, 
    8.05, 9.825, 15.85, 8.6625, 21, 7.75, 18.75, 7.775, 25.4667, 
    7.8958, 6.8583, 90, 0, 7.925, 8.05, 32.5, 13, 13, 24.15, 
    7.8958, 7.7333, 7.875, 14.4, 20.2125, 7.25, 26, 26, 7.75, 
    8.05, 26.55, 16.1, 26, 7.125, 55.9, 120, 34.375, 18.75, 263, 
    10.5, 26.25, 9.5, 7.775, 13, 8.1125, 81.8583, 19.5, 26.55, 
    19.2583, 30.5, 27.75, 19.9667, 27.75, 89.1042, 8.05, 7.8958, 
    26.55, 51.8625, 10.5, 7.75, 26.55, 8.05, 38.5, 13, 8.05, 
    7.05, 0, 26.55, 7.725, 19.2583, 7.25, 8.6625, 27.75, 13.7917, 
    9.8375, 52, 21, 7.0458, 7.5208, 12.2875, 46.9, 0, 8.05, 9.5875, 
    91.0792, 25.4667, 90, 29.7, 8.05, 15.9, 19.9667, 7.25, 30.5, 
    49.5042, 8.05, 14.4583, 78.2667, 15.1, 151.55, 7.7958, 8.6625, 
    7.75, 7.6292, 9.5875, 86.5, 108.9, 26, 26.55, 22.525, 56.4958, 
    7.75, 8.05, 26.2875, 59.4, 7.4958, 34.0208, 10.5, 24.15, 
    26, 7.8958, 93.5, 7.8958, 7.225, 57.9792, 7.2292, 7.75, 10.5, 
    221.7792, 7.925, 11.5, 26, 7.2292, 7.2292, 22.3583, 8.6625, 
    26.25, 26.55, 106.425, 14.5, 49.5, 71, 31.275, 31.275, 26, 
    106.425, 26, 26, 13.8625, 20.525, 36.75, 110.8833, 26, 7.8292, 
    7.225, 7.775, 26.55, 39.6, 227.525, 79.65, 17.4, 7.75, 7.8958, 
    13.5, 8.05, 8.05, 24.15, 7.8958, 21.075, 7.2292, 7.8542, 
    10.5, 51.4792, 26.3875, 7.75, 8.05, 14.5, 13, 55.9, 14.4583, 
    7.925, 30, 110.8833, 26, 40.125, 8.7125, 79.65, 15, 79.2, 
    8.05, 8.05, 7.125, 78.2667, 7.25, 7.75, 26, 24.15, 33, 0, 
    7.225, 56.9292, 27, 7.8958, 42.4, 8.05, 26.55, 15.55, 7.8958, 
    30.5, 41.5792, 153.4625, 31.275, 7.05, 15.5, 7.75, 8.05, 
    65, 14.4, 16.1, 39, 10.5, 14.4542, 52.5542, 15.7417, 7.8542, 
    16.1, 32.3208, 12.35, 77.9583, 7.8958, 7.7333, 30, 7.0542, 
    30.5, 0, 27.9, 13, 7.925, 26.25, 39.6875, 16.1, 7.8542, 69.3, 
    27.9, 56.4958, 19.2583, 76.7292, 7.8958, 35.5, 7.55, 7.55, 
    7.8958, 23, 8.4333, 7.8292, 6.75, 73.5, 7.8958, 15.5, 13, 
    113.275, 133.65, 7.225, 25.5875, 7.4958, 7.925, 73.5, 13, 
    7.775, 8.05, 52, 39, 52, 10.5, 13, 0, 7.775, 8.05, 9.8417, 
    46.9, 512.3292, 8.1375, 76.7292, 9.225, 46.9, 39, 41.5792, 
    39.6875, 10.1708, 7.7958, 211.3375, 57, 13.4167, 56.4958, 
    7.225, 26.55, 13.5, 8.05, 7.7333, 110.8833, 7.65, 227.525, 
    26.2875, 14.4542, 7.7417, 7.8542, 26, 13.5, 26.2875, 151.55, 
    15.2458, 49.5042, 26.55, 52, 9.4833, 13, 7.65, 227.525, 10.5, 
    15.5, 7.775, 33, 7.0542, 13, 13, 53.1, 8.6625, 21, 7.7375, 
    26, 7.925, 211.3375, 18.7875, 0, 13, 13, 16.1, 34.375, 512.3292, 
    7.8958, 7.8958, 30, 78.85, 262.375, 16.1, 7.925, 71, 20.25, 
    13, 53.1, 7.75, 23, 12.475, 9.5, 7.8958, 65, 14.5, 7.7958, 
    11.5, 8.05, 86.5, 14.5, 7.125, 7.2292, 120, 7.775, 77.9583, 
    39.6, 7.75, 24.15, 8.3625, 9.5, 7.8542, 10.5, 7.225, 23, 
    7.75, 7.75, 12.475, 7.7375, 211.3375, 7.2292, 57, 30, 23.45, 
    7.05, 7.25, 7.4958, 29.125, 20.575, 79.2, 7.75, 26, 69.55, 
    30.6958, 7.8958, 13, 25.9292, 8.6833, 7.2292, 24.15, 13, 
    26.25, 120, 8.5167, 6.975, 7.775, 0, 7.775, 13, 53.1, 7.8875, 
    24.15, 10.5, 31.275, 8.05, 0, 7.925, 37.0042, 6.45, 27.9, 
    93.5, 8.6625, 0, 12.475, 39.6875, 6.95, 56.4958, 37.0042, 
    7.75, 80, 14.4542, 18.75, 7.2292, 7.8542, 8.3, 83.1583, 8.6625, 
    8.05, 56.4958, 29.7, 7.925, 10.5, 31, 6.4375, 8.6625, 7.55, 
    69.55, 7.8958, 33, 89.1042, 31.275, 7.775, 15.2458, 39.4, 
    26, 9.35, 164.8667, 26.55, 19.2583, 7.2292, 14.1083, 11.5, 
    25.9292, 69.55, 13, 13, 13.8583, 50.4958, 9.5, 11.1333, 7.8958, 
    52.5542, 5, 9, 24, 7.225, 9.8458, 7.8958, 7.8958, 83.1583, 
    26, 7.8958, 10.5167, 10.5, 7.05, 29.125, 13, 30, 23.45, 30, 
    7.75)), class = "data.frame", row.names = c(NA, -891L))
attach(Titanic)
```
::: {.hidden}
\let\OldTexttt\texttt
\renewcommand{\txt}[1]{\OldTexttt{\color{brown}{#1}}}
:::

# Inferential Statistics (III)

This week, let's delve into **hypothesis testing for comparing two groups**. In this lab, let us presume the assumptions for the hypothesis testings are satisfied, e.g., random sampling and independence.

## Titanic Data Set

On April 15, 1912, the RMS Titanic, heralded as “unsinkable,” met its tragic fate during its maiden voyage after striking an iceberg. The insufficient number of lifeboats onboard sealed the fate of many, claiming 1,502 lives out of the 2,224 passengers and crew. Survival, while partly a matter of chance, also reflected stark disparities, with some groups having a significantly greater likelihood of making it to safety.

The data set $\txt{Titanic}$ contains the passenger information ("Name" variable was removed).

```{r,eval=FALSE}
01. Survived: Survival Status (0 = No, 1= Yes)
02. Pclass:   Ticket Class (1 = 1st, 2 = 2nd, 3 = 3rd)
03. Gender:   Gender  
04. Age:      Age in Years 
05. SibSp:    Number of siblings / spouses aboard the Titanic 
06. Parch:    Number of parents / children aboard the Titanic   
07. Ticket:   Ticket Number 
08. Fare:     Passenger Fare
```

Given a dataset, one of the most intriguing target parameters to examine is the [survival rate]{style="color:blue;"}: the proportion of passengers within a group who survived. This proportion is often represented using the class notation [p]{style="color:blue;"}. Specifically, our goal is to compare survival rates across various groups to uncover patterns or disparities.

## Gender Disparity

Let us consider the gender difference in the survival rate. We can first take a look at the contingency table. Let us define the following variables: $\hat{p}_f$ is the sample survival rate of female group, $\hat{p}_m$ is the sample survival rate of male group, where $X_f$ the number of survived passengers in female group, $X_m$ the number of survived passengers in male group, $n_f$ the number of female passengers, and $n_m$ the number of male passengers.

```{webr-r}
print(nf<-sum(Gender=="female"))
print(xf<-sum(Survived==1 & Gender=="female"))
print(nm<-sum(Gender=="male"))
print(xm<-sum(Survived==1 & Gender=="male"))
print(pf<-xf/nf)
print(pm<-xm/nm)
```

Note that this can be easily summarized by a contingency table.

```{webr-r}
TBL1<-table(Gender,Survived)
TBL2<-prop.table(TBL1, margin = 1)
print.table(TBL2)
```

Observe that the proportion of female survivors is greatly larger than that of male survivors. Then, let us see whether we can statistically confirm this difference.

### Setting up Hypotheses

We want to confirm whether the survival rate of female group $p_f$ is larger than that of male group $p_m$: \begin{align}
H_0:\; p_f-p_m \le 0\; \;\;\text{vs.}&\;\;H_a:\; p_f-p_m > 0 ,\\
\;\;(i.e.,\;\;H_0:\; p_f \le p_m \;\;\text{vs.}&\;\;H_a:\; p_f>p_m).
\end{align}

### Test Statistic

We set up the following test statistic $$
z^*=\frac{(\hat{p}_f-\hat{p}_m)-0}{\sqrt{\hat{p}(1-\hat{p})(1/n_1+1/n_2)}},
$$ where $\hat{p}=\frac{X_f+X_m}{n_f+n_m}$ with $X_f$ the number of survived passengers in female group, $X_m$ the number of survived passengers in male group, $n_f$ the number of female passengers, and $n_m$ the number of male passengers.

```{webr-r}
print(phat<-(xf+xm)/(nf+nm))
print(z.star<-(pf-pm)/sqrt(phat*(1-phat)*(1/nf+1/nm)))
```

It is worth noting that the observed z-test statistic is remarkably large, so we can expect a very small p-value.

### p-value

This is a **right-tailed** test based on **z** test statistic. Similar to the previous lab, we use the function $\txt{pnorm()}$ provides us the left-tail probability, so $$
\text{p-value}=P[Z>z^*]\stackrel{\textsf{R}}{=}\texttt{1-pnorm(z.star)}.
$$

```{webr-r}
print(p.val<-1-pnorm(z.star))
```

The p-value is essentially **zero**!, which means we can comfortably reject the null hypothesis for any significance level. The interpretation should align with the context of the problem. At any significance level, there is sufficient evidence to conclude that a gender disparity exists in the survival rates of the Titanic shipwreck.

## Socioeconomic Status Disparity

Let us now consider the socioeconomic status difference based on the proxy variable, **ticket class**. Let us define the following variables: $\hat{p}_1$ is the sample survival rate of 1st class group, $\hat{p}_2$ is the sample survival rate of 2nd class group, where $X_1$ the number of survived passengers in 1st class group, $X_2$ the number of survived passengers in 2nd class group, $n_1$ the number of 1st class passengers, and $n_2$ the number of 2nd class passengers.

```{webr-r}
print(n1<-sum(Pclass==1))
print(x1<-sum(Survived==1 & Pclass==1))
print(n2<-sum(Pclass==2))
print(x2<-sum(Survived==1 & Pclass==2))
print(p1<-x1/n1)
print(p2<-x2/n2)
```

### Setting up Hypotheses

We want to confirm whether the survival rate of the 1st class group $p_1$ is larger than that of the 2nd class group $p_2$: \begin{align}
H_0:\; p_1-p_2 \le 0\; \;\;\text{vs.}&\;\;H_a:\; p_1-p_2 > 0 ,\\
\;\;(i.e.,\;\;H_0:\; p_1 \le p_2 \;\;\text{vs.}&\;\;H_a:\; p_1>p_2).
\end{align}

### Test Statistic and p-value

We set up the following test statistic $$
z^*=\frac{(\hat{p}_1-\hat{p}_2)-0}{\sqrt{\hat{p}(1-\hat{p})(1/n_1+1/n_2)}},
$$ where $\hat{p}=\frac{X_1+X_2}{n_1+n_2}$ with $X_1$ the number of survived passengers in the 1st class group, $X_2$ the number of survived passengers in the 2nd class group, $n_1$ the number of the 1st class passengers, and $n_2$ the number of the 2nd class passengers.

```{webr-r}
print(phat<-(x1+x2)/(n1+n2))
print(z.star<-(p1-p2)/sqrt(phat*(1-phat)*(1/n1+1/n2)))
print(p.val<-1-pnorm(z.star))
```

What would you be your conclusion and interpretation?

## Lab Questions

Let us complete the investigation regarding the socioeconomic status difference by comparing 2nd and 3rd classes in the **ticket class** variable.

1.  Choose the right form of the null and alternative hypotheses.

<!-- -->

i) $H_0:\; p_2-p_3 \ge 0\; \;\;\text{vs.}\;\;H_a:\; p_2-p_3 < 0$
ii) $H_0:\; p_2-p_3 > 0\; \;\;\text{vs.}\;\;H_a:\; p_2-p_3 \le 0$
iii)  $H_0:\; p_2-p_3 \le 0\; \;\;\text{vs.}\;\;H_a:\; p_2-p_3 > 0$
iv) $H_0:\; p_2-p_3 < 0\; \;\;\text{vs.}\;\;H_a:\; p_2-p_3 \ge 0$
<!-- -->

2.  Define the relevant variables.

```{webr-r}
n2<-
x2<-
n3<-
x3<-
p2<-
p3<-
```

3.  Compute the test-statistic and calculate the p-value.

```{webr-r}

```

4.  Make a conclusion and choose the correct interpretation.

<!-- -->

i)  Reject $H_0$. There is enough evidence to claim that there eixsts socioeconomic disparity in the survival rates of the Titanic shipwreck.
ii) Reject $H_0$. There is not enough evidence to claim that there eixsts socioeconomic disparity in the survival rates of the Titanic shipwreck.
iii) Fail to reject $H_0$. There is enough evidence to claim that there eixsts socioeconomic disparity in the survival rates of the Titanic shipwreck.
iv) Fail to teject $H_0$. There is not enough evidence to claim that there eixsts socioeconomic disparity in the survival rates of the Titanic shipwreck.


**Click [HERE](https://coursesite.lehigh.edu/mod/quiz/view.php?id=6024495){target="_blank"} to submit your answers.**
